server:
  port: 8080
  servlet:
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/spring
    username: root
    password: 1234
    driver-class-name: com.mysql.cj.jdbc.Driver


  jpa:
    hibernate:
      ddl-auto: create
    properties:
      hibernate:
        default_batch_fetch_size: 1000
        format_sql: true
        show_sql: true
    open-in-view: false
    defer-datasource-initialization: true

  sql:
    init:
      mode: always


logging.level:
  org.example.inventorysystem: debug
  org.hibernate.SQL: debug
  org.hibernate.type: trace